import { CustomerProfile, TeapotConfig } from "@/types/cafe";

export const TEAPOTS: TeapotConfig[] = [
  {
    id: "glass",
    name: "Artisan Borosilicate Glass Pot",
    nameTh: "กาแก้วใสทนความร้อนเป่ามือ",
    material: "Clear Glass",
    materialTh: "แก้วบอโรซิลิเกตใส",
    desc: "Observe tea leaves swirling and liquor hue evolving in pristine clarity.",
    descTh: "มองเห็นใบชาเต้นระบำและสีน้ำชาค่อยๆ เข้มขึ้นอย่างชัดเจน",
    icon: "🫖",
    bestFor: "White, Green & Herbal Teas",
    colorHex: "#e2e8f0",
  },
  {
    id: "kyusu",
    name: "Tokoname Ceramic Kyusu",
    nameTh: "กาญี่ปุ่นมีด้ามจับโทโกนาเมะ (Kyusu)",
    material: "Japanese Clay",
    materialTh: "ดินเหนียวญี่ปุ่นเคลือบหยาบ",
    desc: "Ergonomic side-handled teapot with built-in clay mesh filter.",
    descTh: "กาด้ามข้างสไตล์ญี่ปุ่นพร้อมตะแกรงดินในตัว รินน้ำชารวดเร็ว",
    icon: "🍵",
    bestFor: "Sencha, Hojicha & Gyokuro",
    colorHex: "#854d0e",
  },
  {
    id: "zisha",
    name: "Yixing Purple Clay (Zisha)",
    nameTh: "กาดินม่วงอี๋ซิงโบราณ (Zisha)",
    material: "Yixing Purple Clay",
    materialTh: "ดินม่วงจื่อซาแท้",
    desc: "Micro-porous clay retains deep warmth and rounds out bitter tannins.",
    descTh: "เนื้อดินรูพรุนระดับไมโครช่วยกักเก็บความร้อนสูงและลดความฝาดของชา",
    icon: "🏺",
    bestFor: "Wuyi Rock Oolong & Aged Pu-erh",
    colorHex: "#713f12",
  },
  {
    id: "porcelain",
    name: "Hakuji White Porcelain Pot",
    nameTh: "กาน้ำชาพอร์ซเลนสีขาวนวล (Hakuji)",
    material: "Glazed Porcelain",
    materialTh: "พอร์ซเลนเคลือบเงาขาวบริสุทธิ์",
    desc: "Smooth, non-porous glazed surface delivers the truest, crispest aroma.",
    descTh: "ผิวเคลือบเรียบเนียน สะท้อนกลิ่นหอมของชาดอกไม้และชาดำได้อย่างเที่ยงตรง",
    icon: "🫖",
    bestFor: "Earl Grey, Assam & Floral Blends",
    colorHex: "#f8fafc",
  },
];

export const CAFE_CUSTOMERS: CustomerProfile[] = [
  {
    id: "mochi",
    name: "Mochi the Cafe Cat",
    nameTh: "น้องแมวโมจิ (Mochi)",
    avatarEmoji: "🐱",
    role: "Resident Tea Connoisseur",
    roleTh: "ลูกค้าประจำ & เจ้าของร้านตัวจริง",
    bio: "A round, fluffy calico cat who sleeps near the kettle steam. Has a sweet tooth and adores cozy steamed milk.",
    bioTh: "แมวสามสีตัวกลมที่ชอบนอนซุกไออุ่นข้างกาน้ำชา ชอบรสหวานนุ่มนวลและฟองนมนุ่มฟูเป็นพิเศษ",
    orderDialogue: "Meow~ It is windy outside! May I have a warm, soothing tea latte? Floral, sweet, not bitter at all please!",
    orderDialogueTh: "เหมียว~ ข้างนอกลมพัดแรงจัง... ขอดื่มชานมอุ่นๆ หวานละมุน กลิ่นหอมดอกไม้ ไม่เอาขมฝาดเลยนะเมี้ยว!",
    favoriteNotes: "Sweetness, floral aroma, silky foam",
    favoriteNotesTh: "หวานละมุน, กลิ่นดอกไม้หอม, ฟองนมนุ่ม",
    requiredStyle: "latte",
    targetTemp: 85,
    targetSteepSec: 90,
    suggestedTeapot: "porcelain",
    suggestedCup: "latte",
    targetRadar: {
      sweetness: 8,
      aroma: 9,
      body: 7,
      bitterness: 2,
      clarity: 4,
    },
    preferredTeaNames: ["Provence French Lavender 🇫🇷", "Bavarian Chamomile 🇩🇪", "Assam Golden Tips 🇮🇳"],
  },
  {
    id: "kenji",
    name: "Grandpa Kenji",
    nameTh: "คุณลุงเคนจิ (Kenji)",
    avatarEmoji: "👴",
    role: "Retired Kyoto Botanist",
    roleTh: "นักพฤกษศาสตร์เกษียณจากเกียวโต",
    bio: "Practiced the way of tea for 50 years. Appreciates traditional roasted notes, deep earthiness, and proper steeping discipline.",
    bioTh: "ศึกษาศาสตร์แห่งชามานานกว่า 50 ปี ชื่นชอบกลิ่นคั่วหอมลึก ดินหินภูเขา และความพิถีพิถันของอุณหภูมิน้ำ",
    orderDialogue: "Greetings young brewer. Today I long for a contemplative roasted brew. Deep body, rich aroma, steeped at exactly 80–85°C.",
    orderDialogueTh: "สวัสดีบาริสต้าหนุ่ม วันนี้ลุงอยากได้ชาร้อนรสเข้มลึก กลิ่นคั่วหอมกรุ่น บอดี้แน่นๆ สกัดที่อุณหภูมิ 80–85°C พอดีๆ นะ",
    favoriteNotes: "Roasted malt, mineral depth, lingering finish",
    favoriteNotesTh: "กลิ่นคั่วหอม, มิติแร่ธาตุหิน, รสหวานติดปลายลิ้น",
    requiredStyle: "hot",
    targetTemp: 85,
    targetSteepSec: 120,
    suggestedTeapot: "zisha",
    suggestedCup: "chawan",
    targetRadar: {
      sweetness: 4,
      aroma: 9,
      body: 8,
      bitterness: 4,
      clarity: 6,
    },
    preferredTeaNames: ["Wuyi Da Hong Pao Rock Oolong 🇨🇳", "Kyoto Roasted Hojicha 🇯🇵", "Yunnan Vintage Pu-erh 🇨🇳"],
  },
  {
    id: "hana",
    name: "Hana",
    nameTh: "น้องฮานะ (Hana)",
    avatarEmoji: "📚",
    role: "Architecture Student",
    roleTh: "นักศึกษาสถาปัตยกรรมศาสตร์",
    bio: "Surviving exam week on drafting tables. She needs an ultra-refreshing, crystal-clear iced brew with uplifting citrus-floral notes.",
    bioTh: "กำลังปั่นแบบทีสิสโต้รุ่ง ต้องการชาเย็นใสแจ๋ว ดื่มแล้วตื่นตา กลิ่นหอมสดชื่นกระปรี้กระเปร่า ไม่หนักท้อง",
    orderDialogue: "Hello! Big exam tomorrow and my brain is toast... Can you make me an iced, crisp, vibrant tea with floral clarity?",
    orderDialogueTh: "สวัสดีค่า! พรุ่งนี้มีส่งธีสิส สมองเริ่มตึ้บแล้ว... ช่วยชงชาเย็นใสๆ เปรี้ยวหอมสดชื่น กลิ่นดอกไม้ ปลุกสมองให้หน่อยนะคะ!",
    favoriteNotes: "Vibrant clarity, high aroma, cooling ice sphere",
    favoriteNotesTh: "ใสสะอาดสดชื่น, กลิ่นหอมฟุ้ง, น้ำแข็งก้อนกลมเย็นฉ่ำ",
    requiredStyle: "iced",
    targetTemp: 80,
    targetSteepSec: 75,
    suggestedTeapot: "glass",
    suggestedCup: "tumbler",
    targetRadar: {
      sweetness: 5,
      aroma: 9,
      body: 4,
      bitterness: 2,
      clarity: 9,
    },
    preferredTeaNames: ["Nile Valley Hibiscus 🇪🇬", "Alishan High Mountain Oolong 🇹🇼", "Classic Earl Grey Bergamot 🇬🇧"],
  },
  {
    id: "celeste",
    name: "Madame Céleste",
    nameTh: "มาดามเซเลสต์ (Céleste)",
    avatarEmoji: "🎨",
    role: "Parisian Master Perfumer",
    roleTh: "นักปรุงน้ำหอมจากปารีส",
    bio: "Travels the world for olfactory inspirations. Loves complex top-notes and ethereal white tea delicacy.",
    bioTh: "เดินทางทั่วโลกเพื่อตามหากลิ่นหอมหายาก หลงใหลชาขาวชั้นยอดและชั้นเชิงของกลิ่นหอมซับซ้อนที่เปลี่ยนตามอุณหภูมิ",
    orderDialogue: "Bonjour! I am seeking a symphony for my nose. Gentle white tea or honeyed oolong with layered floral aromatics.",
    orderDialogueTh: "บงชูร์! วันนี้ฉันตามหาบทกวีแห่งกลิ่นหอม ขอชาขาวชั้นเลิศหรือชาอู่หลงน้ำผึ้งที่หอมละมุนดั่งสวนดอกไม้ในฤดูใบไม้ผลิ",
    favoriteNotes: "Ethereal honey blossom, high clarity, subtle sweetness",
    favoriteNotesTh: "กลิ่นน้ำผึ้งดอกไม้ป่า, ชาใสประกายทอง, หวานละมุนบางเบา",
    requiredStyle: "hot",
    targetTemp: 75,
    targetSteepSec: 150,
    suggestedTeapot: "glass",
    suggestedCup: "mug",
    targetRadar: {
      sweetness: 7,
      aroma: 10,
      body: 4,
      bitterness: 2,
      clarity: 9,
    },
    preferredTeaNames: ["Fujian Silver Needle (Baihao) 🇨🇳", "Oriental Beauty Honey Oolong 🇹🇼", "Provence French Lavender 🇫🇷"],
  },
  {
    id: "ryu",
    name: "Master Ryu",
    nameTh: "อาจารย์ริว (Master Ryu)",
    avatarEmoji: "🧘",
    role: "Zen Hermit & Tea Master",
    roleTh: "ปรมาจารย์เซนแห่งวิถีชา",
    bio: "Practices Chanoyu meditation in the mist mountains. Highly values energetic balance, deep umami, and ceremonial matcha foam.",
    bioTh: "บำเพ็ญภาวนาในหุบเขาเมฆหมอก ให้ความสำคัญกับความสมดุล รสอูมามิของชาเขียว และฟองมัทฉะที่ละเอียดดั่งแพรไหม",
    orderDialogue: "One cup, one encounter (Ichigo Ichie). Prepare for me a vibrant ceremonial green tea, whisked with sincere focus.",
    orderDialogueTh: "หนึ่งถ้วย หนึ่งวาระ (อิชิโกะ อิชิเอะ)... ช่วยตีชาเขียวมัทฉะพิธีการด้วยจิตอันสงบนิ่ง ให้เกิดฟองนุ่มละมุนแก่ข้าเถิด",
    favoriteNotes: "Rich umami, silky microfoam, deep jade vitality",
    favoriteNotesTh: "รสอูมามิเข้มข้น, ฟองไมโครโฟมเนียนนุ่ม, สีเขียวมรกตสดใส",
    requiredStyle: "hot",
    targetTemp: 80,
    targetSteepSec: 60,
    suggestedTeapot: "kyusu",
    suggestedCup: "chawan",
    targetRadar: {
      sweetness: 5,
      aroma: 8,
      body: 8,
      bitterness: 5,
      clarity: 5,
    },
    preferredTeaNames: ["Kyoto Uji Ceremonial Matcha 🇯🇵", "Shizuoka Sencha 🇯🇵", "Kyoto Roasted Hojicha 🇯🇵"],
  },
];
